admin vê produtos das lojas incompleto
error CS1061: 'Loja' does not contain a definition for 'Produtos' and no accessible extension method 'Produtos' accepting a first argument of type 'Loja' could be found (are you missing a using directive or an assembly reference?)